import os

name = input("PACKAGE NAME: ")
file = open("package.txt", "a")
file.write("sudo apt -y install ")
file.write(name)
file.close()
file = open("package.txt", "r")
os.system(file.read())
file.close()
os.system("sudo rm package.txt")

file = open("package.txt", "a")
file.write("sudo snap install ")
file.write(name)
file.close()
file = open("package.txt", "r")
os.system(file.read())
file.close()
os.system("sudo rm package.txt")

file = open("package.txt", "a")
file.write("sudo snap install --classic ")
file.write(name)
file.close()
file = open("package.txt", "r")
os.system(file.read())
file.close()
os.system("sudo rm package.txt")
